# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab1.sizePolicy().hasHeightForWidth())
        self.tab1.setSizePolicy(sizePolicy)
        self.tab1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab1.setObjectName("tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.delete_button = QtWidgets.QPushButton(self.tab1)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 6, 2, 1, 1)
        self.folder_text = QtWidgets.QLineEdit(self.tab1)
        self.folder_text.setText("")
        self.folder_text.setObjectName("folder_text")
        self.gridLayout.addWidget(self.folder_text, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.progress_bar_list = QtWidgets.QProgressBar(self.tab1)
        self.progress_bar_list.setProperty("value", 0)
        self.progress_bar_list.setObjectName("progress_bar_list")
        self.gridLayout.addWidget(self.progress_bar_list, 3, 2, 1, 1)
        self.add_one_image_button = QtWidgets.QPushButton(self.tab1)
        self.add_one_image_button.setObjectName("add_one_image_button")
        self.gridLayout.addWidget(self.add_one_image_button, 2, 0, 1, 1)
        self.one_image_text = QtWidgets.QLineEdit(self.tab1)
        self.one_image_text.setText("")
        self.one_image_text.setObjectName("one_image_text")
        self.gridLayout.addWidget(self.one_image_text, 1, 0, 1, 1)
        self.add_folder_button = QtWidgets.QPushButton(self.tab1)
        self.add_folder_button.setObjectName("add_folder_button")
        self.gridLayout.addWidget(self.add_folder_button, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.list_of_images = QtWidgets.QListView(self.tab1)
        self.list_of_images.setViewMode(QtWidgets.QListView.ListMode)
        self.list_of_images.setObjectName("list_of_images")
        self.gridLayout.addWidget(self.list_of_images, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.wrong_data_error_label = QtWidgets.QLabel(self.tab1)
        self.wrong_data_error_label.setText("")
        self.wrong_data_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wrong_data_error_label.setObjectName("wrong_data_error_label")
        self.gridLayout.addWidget(self.wrong_data_error_label, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab2.sizePolicy().hasHeightForWidth())
        self.tab2.setSizePolicy(sizePolicy)
        self.tab2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab2.setObjectName("tab2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.check_box_edge = QtWidgets.QCheckBox(self.tab2)
        self.check_box_edge.setObjectName("check_box_edge")
        self.verticalLayout.addWidget(self.check_box_edge)
        self.check_box_blurr = QtWidgets.QCheckBox(self.tab2)
        self.check_box_blurr.setObjectName("check_box_blurr")
        self.verticalLayout.addWidget(self.check_box_blurr)
        self.button_divide = QtWidgets.QPushButton(self.tab2)
        self.button_divide.setObjectName("button_divide")
        self.verticalLayout.addWidget(self.button_divide)
        self.progress_bar_groups = QtWidgets.QProgressBar(self.tab2)
        self.progress_bar_groups.setProperty("value", 0)
        self.progress_bar_groups.setObjectName("progress_bar_groups")
        self.verticalLayout.addWidget(self.progress_bar_groups)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.button_clear_divide = QtWidgets.QPushButton(self.tab2)
        self.button_clear_divide.setObjectName("button_clear_divide")
        self.verticalLayout.addWidget(self.button_clear_divide)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_group_a = QtWidgets.QLabel(self.tab2)
        self.label_group_a.setObjectName("label_group_a")
        self.gridLayout_11.addWidget(self.label_group_a, 0, 0, 1, 1)
        self.label_group_b = QtWidgets.QLabel(self.tab2)
        self.label_group_b.setObjectName("label_group_b")
        self.gridLayout_11.addWidget(self.label_group_b, 0, 1, 1, 1)
        self.list_widget_a = QtWidgets.QListWidget(self.tab2)
        self.list_widget_a.setObjectName("list_widget_a")
        self.gridLayout_11.addWidget(self.list_widget_a, 1, 0, 1, 1)
        self.list_widget_b = QtWidgets.QListWidget(self.tab2)
        self.list_widget_b.setObjectName("list_widget_b")
        self.gridLayout_11.addWidget(self.list_widget_b, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_11, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab3.sizePolicy().hasHeightForWidth())
        self.tab3.setSizePolicy(sizePolicy)
        self.tab3.setObjectName("tab3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.check_box_all = QtWidgets.QCheckBox(self.tab3)
        self.check_box_all.setChecked(True)
        self.check_box_all.setObjectName("check_box_all")
        self.verticalLayout_3.addWidget(self.check_box_all)
        self.check_box_a = QtWidgets.QCheckBox(self.tab3)
        self.check_box_a.setObjectName("check_box_a")
        self.verticalLayout_3.addWidget(self.check_box_a)
        self.check_box_b = QtWidgets.QCheckBox(self.tab3)
        self.check_box_b.setObjectName("check_box_b")
        self.verticalLayout_3.addWidget(self.check_box_b)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.button_clear_segment = QtWidgets.QPushButton(self.tab3)
        self.button_clear_segment.setObjectName("button_clear_segment")
        self.gridLayout_3.addWidget(self.button_clear_segment, 5, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.list_edges = QtWidgets.QListWidget(self.tab3)
        self.list_edges.setObjectName("list_edges")
        self.gridLayout_4.addWidget(self.list_edges, 1, 0, 1, 1)
        self.list_regions = QtWidgets.QListWidget(self.tab3)
        self.list_regions.setObjectName("list_regions")
        self.gridLayout_4.addWidget(self.list_regions, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 3, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.check_box_edge_seg = QtWidgets.QCheckBox(self.tab3)
        self.check_box_edge_seg.setObjectName("check_box_edge_seg")
        self.verticalLayout_2.addWidget(self.check_box_edge_seg)
        self.check_box_water = QtWidgets.QCheckBox(self.tab3)
        self.check_box_water.setObjectName("check_box_water")
        self.verticalLayout_2.addWidget(self.check_box_water)
        self.check_box_region = QtWidgets.QCheckBox(self.tab3)
        self.check_box_region.setObjectName("check_box_region")
        self.verticalLayout_2.addWidget(self.check_box_region)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 1)
        self.button_segment = QtWidgets.QPushButton(self.tab3)
        self.button_segment.setObjectName("button_segment")
        self.gridLayout_3.addWidget(self.button_segment, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.text_save_location = QtWidgets.QLineEdit(self.tab3)
        self.text_save_location.setObjectName("text_save_location")
        self.horizontalLayout.addWidget(self.text_save_location)
        self.button_save = QtWidgets.QPushButton(self.tab3)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.progress_bar_seg = QtWidgets.QProgressBar(self.tab3)
        self.progress_bar_seg.setProperty("value", 0)
        self.progress_bar_seg.setObjectName("progress_bar_seg")
        self.gridLayout_3.addWidget(self.progress_bar_seg, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 174, 148))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.checkBox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_4.addWidget(self.checkBox_8)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_4.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 10, 121, 96))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setAutoFillBackground(False)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_5.addWidget(self.checkBox_7)
        self.progressBar = QtWidgets.QProgressBar(self.tab4)
        self.progressBar.setGeometry(QtCore.QRect(330, 60, 521, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 10, 531, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(319, 109, 531, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_8.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 300, 301, 177))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab4, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image segmentation"))
        self.delete_button.setText(_translate("MainWindow", "Usuń"))
        self.folder_text.setPlaceholderText(_translate("MainWindow", "example.jpg"))
        self.label_2.setText(_translate("MainWindow", "Lista obrazów"))
        self.add_one_image_button.setText(_translate("MainWindow", "Dodaj"))
        self.one_image_text.setPlaceholderText(_translate("MainWindow", "example.jpg"))
        self.add_folder_button.setText(_translate("MainWindow", "Dodaj"))
        self.label_4.setText(_translate("MainWindow", "Wyczyść listę obrazów"))
        self.label.setText(_translate("MainWindow", "Podaj lokalizację obrazu"))
        self.label_3.setText(_translate("MainWindow", "Podaj  folder z obrazami"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Dodaj obrazy"))
        self.label_17.setText(_translate("MainWindow", "Wybierz metodę podziału"))
        self.check_box_edge.setText(_translate("MainWindow", "Podział według krawedzi"))
        self.check_box_blurr.setText(_translate("MainWindow", "Podział według rozmycia"))
        self.button_divide.setText(_translate("MainWindow", "Podziel"))
        self.label_5.setText(_translate("MainWindow", "Wyczyść podział"))
        self.button_clear_divide.setText(_translate("MainWindow", "Wyczyść"))
        self.label_group_a.setText(_translate("MainWindow", "Grupa pierwsza"))
        self.label_group_b.setText(_translate("MainWindow", "Grupa druga"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Grupowanie obrazów"))
        self.label_7.setText(_translate("MainWindow", "Wybierz zakres"))
        self.check_box_all.setText(_translate("MainWindow", "Wszystkie"))
        self.check_box_a.setText(_translate("MainWindow", "Grupa pierwsza"))
        self.check_box_b.setText(_translate("MainWindow", "Grupa druga"))
        self.button_clear_segment.setText(_translate("MainWindow", "Wyczyść"))
        self.label_9.setText(_translate("MainWindow", "Pola"))
        self.label_8.setText(_translate("MainWindow", "Krawędzie"))
        self.label_6.setText(_translate("MainWindow", "Wybierz typ"))
        self.check_box_edge_seg.setText(_translate("MainWindow", "Krawędziowa"))
        self.check_box_water.setText(_translate("MainWindow", "Wododziałowa"))
        self.check_box_region.setText(_translate("MainWindow", "Regionowa"))
        self.button_segment.setText(_translate("MainWindow", "Segmentuj"))
        self.label_10.setText(_translate("MainWindow", "Podaj lokalizację zapisu"))
        self.button_save.setText(_translate("MainWindow", "Zapisz wyniki"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Segmentacja"))
        self.label_11.setText(_translate("MainWindow", "Wybierz algorytm"))
        self.checkBox_8.setText(_translate("MainWindow", "Wszystkie"))
        self.checkBox.setText(_translate("MainWindow", "Jaccarda Index"))
        self.checkBox_2.setText(_translate("MainWindow", "F1 Score"))
        self.checkBox_3.setText(_translate("MainWindow", "Explained Variance Score"))
        self.checkBox_4.setText(_translate("MainWindow", "Mean Squared Error"))
        self.label_12.setText(_translate("MainWindow", "Wybierz zakres"))
        self.checkBox_5.setText(_translate("MainWindow", "Wszystkie"))
        self.checkBox_6.setText(_translate("MainWindow", "Grupa pierwsza"))
        self.checkBox_7.setText(_translate("MainWindow", "Grupa druga"))
        self.label_13.setText(_translate("MainWindow", "Folder z wynikami"))
        self.pushButton.setText(_translate("MainWindow", "Ewaluacja"))
        self.label_14.setText(_translate("MainWindow", "Wyniki"))
        self.label_25.setText(_translate("MainWindow", "0.912445"))
        self.label_18.setText(_translate("MainWindow", "D:\\wyniki12345.jpg"))
        self.label_22.setText(_translate("MainWindow", "Explained Variance Score:"))
        self.label_26.setText(_translate("MainWindow", "7.356"))
        self.label_15.setText(_translate("MainWindow", "Szczegóły"))
        self.label_23.setText(_translate("MainWindow", "Mean Squared Error:"))
        self.label_21.setText(_translate("MainWindow", "F1 Score:"))
        self.label_16.setText(_translate("MainWindow", "Ścieżka pliku:"))
        self.label_19.setText(_translate("MainWindow", "Wyniki ewaluacji:"))
        self.label_20.setText(_translate("MainWindow", "Jaccarda Index:"))
        self.label_27.setText(_translate("MainWindow", "2.613"))
        self.label_24.setText(_translate("MainWindow", "0.956834"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindow", "Ewaluacja"))
